make offset always fiest in ctor, crosstested stucts vs type, added s…
SergeyTeplyakov/ObjectLayoutInspector pull request #18
Opened 2019-03-11 16:05 UTC by dzmitry-lahoda

…truct layout methods, type layout works as before (all test are in place), moved out all SUTs for view and reuse, moved sln to build root dir, added nullable test; #15

2019-03-12 16:29 UTC, SergeyTeplyakov requested changes

2019-03-12 16:29 UTC, SergeyTeplyakov commented on src/ObjectLayoutInspector.Tests/FixedTests.cs
> +
nit: redundant empty line.

2019-03-12 16:29 UTC, SergeyTeplyakov commented on src/ObjectLayoutInspector.Tests/InstanceSizeTests.cs
> +            var layout = TypeLayout.GetLayout<ClassEmpty>();
Just curious, maybe `EmptyClass` not `ClassEmpty`?

2019-03-12 16:29 UTC, SergeyTeplyakov commented on src/ObjectLayoutInspector.Tests/NullableTests.cs
> +
nit: empty line.

2019-03-12 16:29 UTC, SergeyTeplyakov commented on src/ObjectLayoutInspector.Tests/Objects/Derived.cs
> +#pragma warning disable 169 // unused fields
I'm fine with this approach, but an alternative is just to use public fields.

2019-03-12 16:29 UTC, SergeyTeplyakov commented on src/ObjectLayoutInspector.Tests/Objects/Derived.cs
> +#pragma warning disable 169 // unused fields
In this case `#pragma warning` would not be needed.

2019-03-12 16:29 UTC, SergeyTeplyakov commented on src/ObjectLayoutInspector.Tests/Objects/Derived.cs
> +#pragma warning disable 169 // unused fields
BTW, I can see that this is just the same it was before, so it is up to you to totally ignore this comment:)

2019-03-12 16:29 UTC, SergeyTeplyakov commented on src/ObjectLayoutInspector.Tests/StructWithExplicitLayoutTests.cs
> +            var structLayout = UnsafeLayout.GetLayout<NotAlignedStruct>();
It is totally fine, but I can see that all these tests are quite similar. I would prefer to extract a helper that will do the validation instead of copy pasting the call over and over again.

2019-03-12 16:29 UTC, SergeyTeplyakov commented on src/ObjectLayoutInspector.Tests/UnsafeLayoutTests.cs
> +            Assert.AreEqual(typeLayout[0].Offset, structLayout[0].Offset);
This is another example where I would prefer code reuse. In this particular case, I would've added an equality function that will compare structlayout and type layout instead of copy and pasting equality logic in all these tests.

2019-03-12 16:29 UTC, SergeyTeplyakov commented on src/ObjectLayoutInspector.Tests/UnsafeLayoutTests.cs
> +
nit: a bunch of empty lines.

2019-03-12 16:29 UTC, SergeyTeplyakov commented on src/ObjectLayoutInspector/StructLayout.cs
> +        /// <typeparam name="T">To to get structure of.</>
I'm totally fine with these type of comments, but I'm also fine without them:).

2019-03-12 16:29 UTC, SergeyTeplyakov commented on src/ObjectLayoutInspector/StructLayout.cs
> +            return AddPaddings<T>(fieldsLayout);
Can this method be implemented on top of GetFieldsLayout? It seems that the entrie implementation can be like this:

`return AddPaddings<T>(GetFieldLayout<T>(recursive, primitives))`

2019-03-12 16:29 UTC, SergeyTeplyakov commented on src/ObjectLayoutInspector/StructLayout.cs
> +                var last = fieldsAndPaddings.LastOrDefault();
Is it possible for `fieldsAndPaddings` to be empty? By looking at this pretty quickly I can't see how it would be possible... If its not possible then `Last` method can be used that will simplify the logic below a bit.

2019-03-12 16:29 UTC, SergeyTeplyakov commented on src/ObjectLayoutInspector/StructLayout.cs
> +                    fieldsAndPaddings.Add(new Padding(lastOffset, paddingSize));
nit: I would slightly prefer to use braces explicitely.

2019-03-12 16:29 UTC, SergeyTeplyakov commented on src/ObjectLayoutInspector/StructLayout.cs
> +                    else break;
nit: explicit braces.

2019-03-12 16:29 UTC, SergeyTeplyakov commented on src/ObjectLayoutInspector/StructLayout.cs
> +
nit: extra empty line.

2019-03-12 16:29 UTC, SergeyTeplyakov commented on src/ObjectLayoutInspector/StructLayout.cs
> +            object value2 = dummy;
it is a little strange to me, that `dummy` value is returned if `fieldsHierarchy` is empty. For me it should be `defaultValue` in this case.

2019-03-12 16:29 UTC, SergeyTeplyakov commented on src/ObjectLayoutInspector/StructLayout.cs
> +            object value2 = dummy;
Or `seed` rather...

2019-03-12 16:29 UTC, SergeyTeplyakov commented on src/ObjectLayoutInspector/StructLayout.cs
> +        private static object GetValueBefore<T>(List<FieldInfo> fieldsHierarchy, T dummy) where T : struct
Am I missing something, because I can't see a difference between `GetValueBefore` and `GetValueAfter` implementations...

2019-03-12 16:54 UTC, dzmitry-lahoda commented on src/ObjectLayoutInspector/StructLayout.cs
> +        private static object GetValueBefore<T>(List<FieldInfo> fieldsHierarchy, T dummy) where T : struct
fixed

2019-03-12 17:57 UTC, dzmitry-lahoda commented on src/ObjectLayoutInspector/StructLayout.cs
> +                var last = fieldsAndPaddings.LastOrDefault();
Last breaks dozen of tests, I guess logic could be simplified, but not that way.

2019-03-12 17:59 UTC, dzmitry-lahoda commented
I fixed many issues. Much more pretty now. Code still complex (so do not see patter to simplify it now, probably during nullables support)

2019-03-14 21:21 UTC, closed without merging

2019-03-14 21:36 UTC, SergeyTeplyakov commented
@dzmitry-lahoda Sorry, was a bit busy at work... Why you decided to close the PR?

2019-03-14 21:45 UTC, dzmitry-lahoda commented
I rewrote all code and will do even more. I guess better to create new pull. As code very very different.

2019-03-14 21:46 UTC, SergeyTeplyakov commented
@dzmitry-lahoda Ok, sounds good. Looking forward to the new PR.

2019-03-14 21:47 UTC, dzmitry-lahoda commented
Except complex padding, i have found need to support nullables and fixed(new C# feature) with non primitive structs (which was hard in previous code). I will fix all this and create pull again.